export default Constraints = {
  SUBTITLE: 'Here is the list of all patients',
  CLINIC: 'Eye Clinic',
  SCHEDULE: 'Appoinments',
  SCHEDULE_subTitle: 'Please select Date',
  UPLOADTXT: 'Add Patient Report',
  UPLOADSUBTXT: 'You can add patient ',
  UPLOADSUBTXT2: 'report details',
  SPH: 'SPH',
  CYL: 'CYL',
  AXIS: 'AXIS',
  VA: 'V/A',
  LEFT: 'Left',
  RIGHT: 'Right',
  REFRACTIONCARD: 'Refraction Card',
  PATIENTDETAILS: 'Patient Details',
  TREATMENT: 'Treatment',
  DIAGNOSIS: 'Diagnosis',
};
